### PR TITLE
Fix #221: improve diagnostics when dereference fails

### LINKED ISSUE #221: Improve diagnostics when a type could not be referenced
In some cases, when a type could not be referenced, the diagnostic message doesn't indicate that (the `undefined` return value will still cause an error, but we also want to know that we couldn't deref the type)

### PR DESCRIPTION
**Pull request by eladb**
In some cases, when a type could not be referenced, the diagnostic 
message doesn't indicate that (the undefined return value will still 
cause an error, but we also want to know that we couldn't deref the 
type)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/jsii/lib/assembler.ts [hunk 1]
```diff
@@ -314,10 +321,10 @@ export class Assembler implements Emitter {
                 continue;
             }
             this._defer(() => {
-                if (!spec.isClassType(this._dereference(ref))) {
+                if (!spec.isClassType(this._dereference(ref, base.symbol.valueDeclaration))) {
                     this._diagnostic(base.symbol.valueDeclaration,
                                     ts.DiagnosticCategory.Error,
-                                    `Base type of ${jsiiType.fqn} is not a class (${spec.describeTypeReference(ref)})`);
+                                    `Base type of ${jsiiType.fqn} is not a class or cannot be dereferenced (${spec.describeTypeReference(ref)})`);
```
Comment (rix0rrr) [inline packages/jsii/lib/assembler.ts]: Make this 'is not exported', that's more in line with what people are thinking about when writing code.

File: packages/jsii/lib/assembler.ts [hunk 2]
```diff
@@ -499,12 +506,14 @@ export class Assembler implements Emitter {
...
-                if (!spec.isInterfaceType(this._dereference(ref))) {
-                    const baseType = this._dereference(ref);
+                const baseType = this._dereference(ref, base.symbol.valueDeclaration);
+                if (!spec.isInterfaceType(baseType)) {
                     if (baseType) {
+                        // tslint:disable:max-line-length
                         this._diagnostic(base.symbol.valueDeclaration,
                                         ts.DiagnosticCategory.Error,
-                                        `Base type of ${jsiiType.fqn} is not an interface (${baseType.kind} ${spec.describeTypeReference(ref)})`);
+                                        `Base type of ${jsiiType.fqn} is not an interface or cannot be dereferenced (${baseType.kind} ${spec.describeTypeReference(ref)})`);
```
Comment (rix0rrr) [inline packages/jsii/lib/assembler.ts]: Same here.

File: packages/jsii/lib/assembler.ts (hunk 1 above)
Comment (rix0rrr) [reply packages/jsii/lib/assembler.ts]: Better yet, suppress the second error message by checking that result of _dereference is not `undefined`.

Comment (eladb) [reply packages/jsii/lib/assembler.ts]: ✔️

File: packages/jsii/lib/assembler.ts (hunk 2 above)
Comment (eladb) [reply packages/jsii/lib/assembler.ts]: ✔️

**Comment by eladb** [comment]
@rix0rrr fixed
