### PR TITLE
fix(jsii): show jsii diagnostics in watch mode and support $tsc problem matcher

### LINKED ISSUE #382: jsii diagnostics are not emitted in "watch" mode

### PR DESCRIPTION
**Pull request by eladb**
Emit jsii diagnostics error when in watch mode, and also format the errors with a
"TS9999" error code so that VSCode's $tsc problem matcher will show them as
"Problems". Prefix "JSII" in the message to distinguish that these are jsii errors.

Fixes #382

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/jsii/lib/utils.ts [hunk 1]
```diff
@@ -24,6 +26,24 @@ export function diagnosticsLogger(logger: log4js.Logger, diagnostic: ts.Diagnost
...
+    const formatDiagnosticsHost = {
+        getCurrentDirectory: () => projectRoot,
+        getCanonicalFileName(fileName: string) { return fileName; },
+        getNewLine() { return '\n'; }
+    };
+
+    const message = diagnostic.file
+                ? ts.formatDiagnosticsWithColorAndContext([diagnostic], formatDiagnosticsHost)
+                : ts.formatDiagnostics([diagnostic], formatDiagnosticsHost);
+    // if (hasDomain(diagnostic)) {
```
Comment (RomainMuller) [inline packages/jsii/lib/utils.ts]: Just drop that :)
