### PR TITLE
fix(kernel): Improve tagged type of wire values

### LINKED ISSUE #345: kernel: return type for unexported types
Someone reported a failing case over email, where we were returning a `Construct` to Java, which should have been a particular L1 class.

Key insight: the type we construct a proxy for depends on the requested type. Compliance test:

```ts
export class PublicClass {
    hello(): void;
}

export interface IPublicInterface {
    bye(): void;
}

export class InbetweenClass extends PublicClass {
}

class PrivateClass extends InbetweenClass implements IPublicInterface {
    public hello() {
        process.stdout.write('Hello\n');
    }

    public bye() {
        process.stdout.write('Bye\n');
    }
}

export class Constructors {
    public static makeClass(): PublicClass {
        return new PrivateClass();
    }

    public static makeInterface(): IPublicInterface {
        return new PrivateClass();
    }
}
```

Given the same object instance:

* `Constructors.makeClass()` should return a proxy object for `InbetweenClass`.
* `Constructors.makeInterface()` should return a proxy object for `IPublicInterface`.

Given:

* The actual type (`PrivateClass`)
* The requested type (`PublicClass` vs. `IPublicInterface`)
* The inheritance hierarchy

We should be returning the most specific type on the inheritance path between actual and requested that is itself `exported`.

### PR DESCRIPTION
**Pull request by RomainMuller**
When passing references across the JSII language boundary, the static
return type of a method is used instead of the runtime type of the
object if they are not the same, even if they are compatible. This
causes issues that make it impossible to up-cast from methods such as
`IConstruct.findChild` that return a super-class that is expected to be
up-casted to it's known dynamic type.

Fixes #345

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

---

TODO:
- [x] Add compliance test

### CODE REVIEW

**Comment by rix0rrr** [comment]
I think we need a test

**Comment by rix0rrr** [comment]
Also don't like how this doesn't cover the intermediate class case. It's not that much more work and covers us for future fuckups.

**Comment by RomainMuller** [comment]
But... does this not cover the "more correct behavior"? I don't see the difference... o_O

**Comment by RomainMuller** [comment]
Added the compliance tests (kernel, Java, C#).

File: packages/jsii-calc/lib/compliance.ts [hunk 1]
```diff
@@ -1232,4 +1232,24 @@ export class JsiiAgent {
     public static get jsiiAgent(): string | undefined {
         return process.env.JSII_AGENT;
     }
-};
\ No newline at end of file
+};
+
+// https://github.com/awslabs/jsii/issues/345
```
Comment (eladb) [inline packages/jsii-calc/lib/compliance.ts]: Add a short explanation here as well

File: packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java [hunk 2]
```diff
@@ -968,6 +973,15 @@ public void receiveInstanceOfPrivateClass() {
         assertTrue(new ReturnsPrivateImplementationOfInterface().getPrivateImplementation().getSuccess());
     }
 
+    @Test
+    public void objRefsAreLabelledUsingWithTheMostCorrectType() {
+        final PublicClass classRef = Constructors.makeClass();
+        final IPublicInterface ifaceRef = Constructors.makeInterface();
+
+        assertTrue(classRef instanceof InbetweenClass);
```
Comment (rix0rrr) [inline packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java]: I don't see how this can be true. But if it works, then it works.

Comment (RomainMuller) [reply packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java]: This property being true is literally the whole point of this change.... 🤔

File: packages/jsii-calc/lib/compliance.ts (hunk 1 above)
Comment (RomainMuller) [reply packages/jsii-calc/lib/compliance.ts]: Sure!
