### PR TITLE
fix(python): support variadic arguments

### LINKED ISSUE #483: Python: Ec2Service.placeSpreadAccross example is broken
The example https://github.com/aws-samples/aws-cdk-examples/tree/master/python/ecs/ecs-service-with-task-placement is broken in Python:

```python
service.place_spread_across(ecs.BuiltInAttributes.AVAILABILITY_ZONE)
```

leads to

```
npx: installed 271 in 3.688s
Traceback (most recent call last):
  File "app.py", line 50, in <module>
    service.place_spread_across([ecs.BuiltInAttributes.AVAILABILITY_ZONE])
  File "/tmp/.venv/lib/python3.6/site-packages/aws_cdk/aws_ecs/__init__.py", line 2683, in place_spread_across
    return jsii.invoke(self, "placeSpreadAcross", [fields])
  File "/tmp/.venv/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 104, in wrapped
    return _recursize_dereference(kernel, fn(kernel, *args, **kwargs))
  File "/tmp/.venv/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 258, in invoke
    args=_make_reference_for_native(self, args),
  File "/tmp/.venv/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 115, in _make_reference_for_native
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/tmp/.venv/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 115, in <listcomp>
    return [_make_reference_for_native(kernel, i) for i in d]
  File "/tmp/.venv/lib/python3.6/site-packages/jsii/_kernel/__init__.py", line 121, in _make_reference_for_native
    d.__jsii__type__ = "Object"
AttributeError: 'tuple' object has no attribute '__jsii__type__'
```

Method is variadic, is that the problem? Or it might be about the constant definition.

https://alpha-docs-aws.amazon.com/CDK/api/preview/docs/@aws-cdk_aws-ecs.Ec2Service.html#placespreadacrossfields-void

### PR DESCRIPTION
**Pull request by garnaat**
Fixes #483 

Handles variadic args and adds a test of VariadicMethod to the compliance tests.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/jsii-pacmak/lib/targets/python.ts [hunk 1]
```diff
@@ -472,7 +472,13 @@ abstract class BaseMethod implements PythonBase {
             paramNames.push(toPythonParameterName(param.name));
         }
```
Comment (eladb) [inline packages/jsii-pacmak/lib/targets/python.ts]: Wouldn't it make more sense to simply check if `param.variadic` is true here and push a different value to `paramNames`?

Comment (garnaat) [reply packages/jsii-pacmak/lib/targets/python.ts]: Yeah. I started with a change proposed in the original issue. Meant to clean it up but forgot.  Testing my updates now.
