### PR TITLE
fix(jsii): detect double interface member declarations

### LINKED ISSUE #340: jsii: do not allow interfaces to redefine members (dotnet does not support it)
Repro:

```ts
intetface A {
  foo: number;
}

interface B extends A {
  foo: number;
}
```

This is legal in typescript but .NET will fail due to `hides inherited member. Use the new keyword if hiding was intended`

### PR DESCRIPTION
**Pull request by rix0rrr**
In C# it's prohibited to declare an interface member
that also exists in an inherited interface. Have jsii
detect this illegal pattern.

Strictly speaking, this only true if we don't overload,
but since we don't support overloading anyway we just
check on the member names, not the types.

Fixes #340.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/jsii/lib/assembler.ts [hunk 1]
```diff
@@ -624,6 +624,27 @@ export class Assembler implements Emitter {
             }
         });
 
+        // Check that no interface declares a member that's already declared
+        // in a base type (not allowed in C#).
```
Comment (costleya) [inline packages/jsii/lib/assembler.ts]: C# allows this. https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/new-modifier

Comment (rix0rrr) [reply packages/jsii/lib/assembler.ts]: Well this is the error I get:
```
@aws-cdk/aws-iam: IRoleProxy.cs(113,21): error CS0111: Type 'IRoleProxy' already defines a member called 'AddToPolicy' with the same parameter types [/tmp/jsii-pacmak-codec20iQw/Amazon.CDK.AWS.IAM/Amazon.CDK.AWS.IAM.csproj]
```

Comment (rix0rrr) [reply packages/jsii/lib/assembler.ts]: Yeah I guess 'new' will do it. I don't get the point of it though, and our C# generator doesn't do the necessary analysis to add the modifier, so I think disallowing in jsii is the easiest  way forward.
