### PR TITLE
fix: remove use of private API

### LINKED ISSUE #350: Get rid of private API use
To parse `tsconfig.json`, the compiler needs a `ParseConfigHost`, which contains functions to inspect the filesystem. Unlike a `CompilerHost`, there is no public factory function to create one.

There is a private function to turn an existing `CompilerHost` into a `ParseConfigHost` which we call today, but we've gotten some signal that this function may be removed in an upcoming version, so we're going to have to implement our own `ParseConfigHost` soon.

https://github.com/awslabs/jsii/blob/4ecf28ceaaf130bd1622765468bc64a43fbb5efd/packages/jsii/lib/compiler.ts#L262

### PR DESCRIPTION
**Pull request by rix0rrr**
Don't use the upstream private API function to turn a `CompilerHost` into a
`ParseConfigHost` anymore; instead, I copied the implementation, which is
simple enough.

Fixes #350.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/jsii/lib/compiler.ts [hunk 1]
```diff
@@ -323,3 +323,18 @@ function nodeJsCompatibleSearchPaths(dir: string): string[] {
 
     return ret;
 }
+
+function parseConfigHostFromCompilerHost(host: ts.CompilerHost): ts.ParseConfigHost {
```
Comment (RomainMuller) [inline packages/jsii/lib/compiler.ts]: Can you add a link to the original implementation? I mean a permalink to the particular location... If it ever needs to be updated, that'll probably help track down where the new version of it lives...
