### PR TITLE
 fix(kernel + java): skip overrides of private methods/properties

### LINKED ISSUE #244: java/kernel: overrides should not be created for private methods/properties
Brought up in: awslabs/aws-cdk#757

When jsii objects are created, property/method overrides should not be defined for private members, both on the native side and on the javascript side.

### PR DESCRIPTION
**Pull request by eladb**
jsii-kernel will ignore override requests for methods/properties that
resolve on the object but are not defined in the public API of the
type.

java runtime will not request overrides for methods/properties that
use "private" accessibility.

Fixes #244

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java [hunk 1]
```diff
@@ -837,6 +838,73 @@ public void returnAbstract() {
...
+            }
+        };
+
+        assertEquals("privateProperty", obj.privatePropertyValue());
+    }
+
+    @Test
+    public void doNotOverridePrivates_property_getter_private() {
+        DoNotOverridePrivates obj = new DoNotOverridePrivates() {
+            private String getPrivateProperty() {
```
Comment (RomainMuller) [inline packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java]: How 'bout the setters?

File: packages/jsii-kernel/lib/kernel.ts [hunk 2]
```diff
@@ -521,10 +531,16 @@ export class Kernel {
...
     }
 
-    private _applyPropertyOverride(obj: any, objref: api.ObjRef, override: api.Override) {
+    private _applyPropertyOverride(obj: any, objref: api.ObjRef, override: api.Override, propInfo?: spec.Property) {
         const self = this;
         const propertyName = override.property!;
 
+        // if this is a private property (i.e. doesn't have `propInfo` the object has a key)
+        if (!propInfo && propertyName in obj) {
+            this._debug(`Skipping override of private property ${propertyName}`);
```
Comment (RomainMuller) [inline packages/jsii-kernel/lib/kernel.ts]: Shouldn't this `throw`? I can't help but think this is the symptom of a bug...

File: packages/jsii-kernel/lib/kernel.ts [hunk 3]
```diff
@@ -570,6 +586,13 @@ export class Kernel {
         const self = this;
         const methodName = override.method!;
 
+        // If this is a private method (doesn't have methodInfo, key resolves on the object), we
+        // are going to skip the override.
+        if (!methodInfo && obj[methodName]) {
+            this._debug(`Skipping override of private method ${methodName}`);
```
Comment (RomainMuller) [inline packages/jsii-kernel/lib/kernel.ts]: Same here...

File: packages/jsii-kernel/lib/kernel.ts [hunk 4]
```diff
@@ -596,6 +619,8 @@ export class Kernel {
                     });
                 }
             });
+        } else if (!methodInfo && Object.keys(obj).includes(methodName)) {
+            throw new Error('boom');
```
Comment (RomainMuller) [inline packages/jsii-kernel/lib/kernel.ts]: Congratulations - you earned yourself a distracting gif of confusing!

File: packages/jsii-kernel/lib/kernel.ts (hunk 2 above)
Comment (eladb) [reply packages/jsii-kernel/lib/kernel.ts]: Not necessarily, there could be case where the user would define a public method in a derived native class with the same name as a private method in a base javascript class. When the native jsii client instantiates the javascript object, it doesn't know that this method is private on the javascript side, do it will pass it as an override (you could argue that the jsii client should only pass overrides for known public methods, but currently this is not the behavior, at least in java).

File: packages/jsii-kernel/lib/kernel.ts (hunk 3 above)
Comment (eladb) [reply packages/jsii-kernel/lib/kernel.ts]: Same response.

File: packages/jsii-kernel/lib/kernel.ts (hunk 4 above)
Comment (eladb) [reply packages/jsii-kernel/lib/kernel.ts]: Oops. Debug code.

File: packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java (hunk 1 above)
Comment (eladb) [reply packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java]: Added

**Comment by eladb** [comment]
@RomainMuller let me know if this looks okay

File: packages/jsii-kernel/lib/kernel.ts (hunk 2 above)
Comment (RomainMuller) [reply packages/jsii-kernel/lib/kernel.ts]: That makes sense to me. I think the front-end code should be a little more educated about the type model it was generated for... So I reckon this should be a `WARN` and not a `DEBUG`.
