### PR TITLE
fix(jsii-runtime): treat "null" as "undefined"

### LINKED ISSUE #282: .NET: null property object support
From @costleya – Requiring code to pass around empty StackProps() param is confusing.  This is a bug in the .NET binding generation code.

### PR DESCRIPTION
**Pull request by eladb**
Since most languages do not have a distinction between "null" and
"undefined", jsii will effectively convert any "null" value passed into
an argument, a property or inside an object to "undefined".

Adds a compliance test to Java and .NET called "NullShouldBeTreatedAsUndefined".

Fixes awslabs/aws-cdk#157
Fixes #282

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java [hunk 1]
```diff
@@ -927,6 +929,18 @@ public void classWithPrivateConstructorAndAutomaticProperties() {
         assertEquals("Hello", obj.getReadOnlyString());
     }
 
+    @Test
+    public void nullShouldBeTreatedAsUndefined() {
+        NullShouldBeTreatedAsUndefined obj = new NullShouldBeTreatedAsUndefined("hello", null);
```
Comment (RomainMuller) [inline packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java]: I'm not even sure the `Jackson` configuration we have would include the `null`s in the generated JSON. But I reckon the intent is still validated, right?

Comment (RomainMuller) [reply packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java]: The POJOs get serialized to JSON before they're sent to the kernel, right? That JSON :)

Comment (eladb) [reply packages/jsii-java-runtime-test/project/src/test/java/software/amazon/jsii/testing/ComplianceTest.java]: Got it. null is serialized to "null"
