### PR TITLE
fix(jsii): Defaulted parameters were not rendered as optional

### LINKED ISSUE #233: Java: method overloads are not generated (regression)
Oddly, method overloads are no longer generated (see CDK `Bucket` constructor, and `Bucket.grantRead` examples)

### PR DESCRIPTION
**Pull request by RomainMuller**
Parameters with a default value were not represented as optional in the assembly
documents due to an oversight when re-writing `jsii`. There was also no coverage
in the test corpus for this use-case, so I've added some.

Fixes #233

### CODE REVIEW

File: packages/jsii-calc/lib/compliance.ts [hunk 1]
```diff
@@ -240,6 +240,10 @@ export class RuntimeTypeChecking {
     public methodWithOptionalArguments(arg1: number, arg2: string, arg3?: Date) {
         arg1; arg2; arg3;
     }
+
+    public methodWithDefaultedArguments(arg1: number = 2, arg2: string, arg3: Date = new Date()) {
```
Comment (eladb) [inline packages/jsii-calc/lib/compliance.ts]: Can you add a test to verify this for ctors as well?

Comment (RomainMuller) [reply packages/jsii-calc/lib/compliance.ts]: Done!
